rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx

    branches:
      except:
        - artoo.io

      notifications:
        irc: "irc.freenode.org#artoo"
